version: '3'

services:
  web:
    container_name: echoes-web
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - mainnet
  postgres:
    container_name: echoes-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    volumes:
      - /postgres-volume:/var/lib/postgresql/data
    networks:
      - mainnet
  adminer:
    container_name: echoes-adminer
    image: adminer
    ports:
      - "5050:8080"
    depends_on:
      - postgres
    networks:
      - mainnet
  redis:
    container_name: echoes-redis  
    image: redis
    ports:
      - '6379:6379'
    networks:
      - mainnet
    volumes: 
      - cache:/data

networks:
  mainnet:
    driver: bridge

volumes:
  postgres-volume:
  cache:
    driver: local