services:
  web:
    container_name: echoes-web
    image: yosaa5782/echoes:0.1
    ports:
      - "80"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - mainnet
  postgres:
    container_name: echoes-postgres
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=fib11235813
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - mainnet
  adminer:
    container_name: echoes-adminer
    image: adminer
    ports:
      - "8080"
    depends_on:
      - postgres
    networks:
      - mainnet
  redis:
    container_name: echoes-redis
    image: redis
    ports:
      - '6379'
    networks:
      - mainnet
    volumes:
      - cache:/data
  nginx:
    container_name: echoes-nginx
    build: 
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./www:/usr/share/nginx/html
    environment:
      - NGINX_HOST=locobase.duckdns.org
    networks:
      - mainnet

networks:
  mainnet:
    driver: bridge

volumes:
  postgres-volume:
  cache:
