services:
  web:
    container_name: echoes-web
    build:
      context: .
      dockerfile: air.dockerfile
    ports:
      - "5000:80"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      - ECHOES_POSTGRES_ADDR=echoes-postgres:5432/echoesdb?sslmode=disable
      - ECHOES_POSTGRES_USER=user
      - ECHOES_POSTGRES_PASS=1234
      - ECHOES_REDIS_ADDR=echoes-redis:6379
    networks:
      - echoes-network
    volumes:
      - ./:/app
    healthcheck:
      test: curl -f http://localhost:80/health || exit 1
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
  redis:
    container_name: echoes-redis
    image: redis
    ports:
      - "5002:6379"
    networks:
      - echoes-network
    volumes:
      - redis-vol:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
  postgres:
    container_name: echoes-postgres
    image: postgres
    ports:
      - "5001:6379"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=echoesdb
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    networks:
      - echoes-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d hjkl_db" ]
      interval: 10s
      timeout: 5s
      retries: 3
  migrate:
    container_name: echoes-migrate
    image: migrate/migrate
    networks:
      - echoes-network
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://user:1234@echoes-postgres:5432/echoesdb?sslmode=disable",
        "up"
      ]
    links:
      - postgres
  adminer:
    container_name: echoes-adminer
    image: adminer
    ports:
      - "5003:8080"
    depends_on:
      - postgres
    networks:
      - echoes-network

networks:
  echoes-network:
    driver: bridge

volumes:
  postgres-vol:
  redis-vol:
