services:
  web:
    container_name: echoes-web
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
      - migrate
    env_file:
      - .env_docker
    networks:
      - mainnet
    volumes:
      - ./templates:/app/templates
      - ./assets:/app/assets
      - ./config.yaml:/app/config.yaml
  postgres:
    container_name: echoes-postgres
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=echoesdb
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - mainnet
  migrate:
    image: migrate/migrate
    networks:
      - mainnet
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://user:1234@echoes-postgres:5432/echoesdb?sslmode=disable",
        "up"
      ]
    links:
      - postgres
  adminer:
    container_name: echoes-adminer
    image: adminer
    ports:
      - "5050:8080"
    depends_on:
      - postgres
    networks:
      - mainnet
  redis:
    container_name: echoes-redis
    image: redis
    ports:
      - '6379'
    networks:
      - mainnet
    volumes:
      - cache:/data

networks:
  mainnet:
    driver: bridge

volumes:
  postgres-volume:
  cache:
